name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  site:
    runs-on: ubuntu-latest
    name: Client CI

    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint
